export enum Organ {
  LIVER = 'LIVER',
  GALLBLADDER = 'GALLBLADDER',
  HEART = 'HEART',
  SMALL_INTESTINE = 'SMALL_INTESTINE',
  SPLEEN = 'SPLEEN',
  STOMACH = 'STOMACH',
  LUNGS = 'LUNGS',
  LARGE_INTESTINE = 'LARGE_INTESTINE',
  KIDNEYS = 'KIDNEYS',
  BLADDER = 'BLADDER',
  PERICARDIUM = 'PERICARDIUM',
  TRIPLE_BURNER = 'TRIPLE_BURNER',
}
